---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-logging

resources:
  - openshift-logging-namespace.yaml
  - openshift-logging-operatorgroup.yaml
  - openshift-logging-subscription.yaml
