apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"

resources:
  - subscription.yaml
  - namespace.yaml
  - rhacs-operator-operatorgroup.yaml
